### ISSUE TITLE
Add custom block devices support for Docker backend

### ISSUE THREAD

**Issue by jieyu** [dcos/dcos-e2e#1155]
To use dcos-docker for testing storage related work, we need a way to automatically add block devices to the agent nodes. The block devices can be backed by loopback devices.

Currently, we're using `dcos-launch`, and it supports `aws_block_device_mappings` like the following:
```yaml
aws_block_device_mappings:
  - DeviceName: /dev/sdc
    Ebs:
      VolumeSize: 2
      DeleteOnTermination: true
      VolumeType: gp2
```

We need something equivalent if we want to switch to use dcos-docker.

cc @nfnt @gpaul @jdef
